// ============================================================
// Модуль 6. Использование встроенных функций
// Примеры на языке DAX (DAX Studio / Power BI)
// Предприятие «Руда+»
// ============================================================

// ============================================================
// 1. МАТЕМАТИЧЕСКИЕ ФУНКЦИИ
// ============================================================

// 1.1 ROUND — округление содержания Fe
EVALUATE
TOPN(5,
    ADDCOLUMNS(
        FILTER(fact_ore_quality,
            fact_ore_quality[date_id] = 20240315),
        "Fe округл. до 1", ROUND(fact_ore_quality[fe_content], 1),
        "Fe округл. до 0", ROUND(fact_ore_quality[fe_content], 0)
    ),
    fact_ore_quality[fe_content], DESC
)

// 1.2 CEILING / FLOOR — округление вверх и вниз
EVALUATE
TOPN(5,
    ADDCOLUMNS(
        FILTER(fact_ore_quality,
            fact_ore_quality[date_id] = 20240315),
        "Fe вверх",  CEILING(fact_ore_quality[fe_content], 1),
        "Fe вниз",   FLOOR(fact_ore_quality[fe_content], 1)
    ),
    fact_ore_quality[fe_content], DESC
)

// 1.3 TRUNC — отсечение
EVALUATE
TOPN(5,
    ADDCOLUMNS(
        FILTER(fact_ore_quality,
            fact_ore_quality[date_id] = 20240315),
        "Fe trunc 1", TRUNC(fact_ore_quality[fe_content], 1),
        "Fe trunc 0", TRUNC(fact_ore_quality[fe_content], 0)
    ),
    fact_ore_quality[fe_content], DESC
)

// 1.4 ABS — абсолютное отклонение от целевого Fe (60%)
EVALUATE
TOPN(10,
    ADDCOLUMNS(
        FILTER(fact_ore_quality,
            fact_ore_quality[date_id] >= 20240301
            && fact_ore_quality[date_id] <= 20240331),
        "Отклонение", fact_ore_quality[fe_content] - 60,
        "Абс. откл.", ABS(fact_ore_quality[fe_content] - 60)
    ),
    ABS(fact_ore_quality[fe_content] - 60), DESC
)

// 1.5 POWER и SQRT
EVALUATE
ADDCOLUMNS(
    FILTER(fact_ore_quality,
        fact_ore_quality[date_id] = 20240315),
    "Кв. откл.", POWER(fact_ore_quality[fe_content] - 60, 2),
    "Корень кв. откл.", SQRT(POWER(fact_ore_quality[fe_content] - 60, 2))
)

// 1.6 SIGN — направление отклонения
EVALUATE
ADDCOLUMNS(
    FILTER(fact_ore_quality,
        fact_ore_quality[date_id] = 20240315
        && fact_ore_quality[shift_id] = 1),
    "Отклонение", fact_ore_quality[fe_content] - 60,
    "Направление", SIGN(fact_ore_quality[fe_content] - 60)
)

// 1.7 MOD — чётность ID
EVALUATE
TOPN(10,
    ADDCOLUMNS(
        fact_production,
        "Чётность",
            IF(MOD(fact_production[production_id], 2) = 0,
               "Чётный", "Нечётный")
    ),
    fact_production[production_id], ASC
)

// 1.8 Математические константы и функции
EVALUATE
ROW(
    "PI", PI(),
    "LN(e)", LN(2.71828),
    "LOG10(100)", LOG10(100),
    "LOG(8, 2)", LOG(8, 2),
    "RAND", RAND()
)


// ============================================================
// 2. АГРЕГАТНЫЕ ФУНКЦИИ
// ============================================================

// 2.1 Базовые агрегаты: сводка добычи за март 2024
EVALUATE
VAR _march =
    FILTER(fact_production,
        fact_production[date_id] >= 20240301
        && fact_production[date_id] <= 20240331)
RETURN
ROW(
    "Записей",      COUNTROWS(_march),
    "Уник. оборуд.", CALCULATE(DISTINCTCOUNT(fact_production[equipment_id]), _march),
    "Уник. операт.", CALCULATE(DISTINCTCOUNT(fact_production[operator_id]), _march),
    "Всего тонн",   CALCULATE(SUM(fact_production[tons_mined]), _march),
    "Ср. тонн",     CALCULATE(AVERAGE(fact_production[tons_mined]), _march),
    "Мин. тонн",    CALCULATE(MIN(fact_production[tons_mined]), _march),
    "Макс. тонн",   CALCULATE(MAX(fact_production[tons_mined]), _march)
)

// 2.2 COUNT vs COUNTROWS vs DISTINCTCOUNT
EVALUATE
VAR _march =
    FILTER(fact_ore_quality,
        fact_ore_quality[date_id] >= 20240301
        && fact_ore_quality[date_id] <= 20240331)
RETURN
ROW(
    "Все строки", COUNTROWS(_march),
    "Не-NULL SiO2", CALCULATE(COUNT(fact_ore_quality[sio2_content]), _march),
    "Уник. сорта", CALCULATE(DISTINCTCOUNT(fact_ore_quality[ore_grade_id]), _march)
)

// 2.3 CONCATENATEX — список оборудования по шахтам (аналог STRING_AGG)
EVALUATE
ADDCOLUMNS(
    VALUES(dim_mine[mine_name]),
    "Оборудование",
        CONCATENATEX(
            FILTER(dim_equipment, dim_equipment[status] = "active"),
            dim_equipment[equipment_name],
            ", ",
            dim_equipment[equipment_name], ASC
        ),
    "Кол-во",
        CALCULATE(
            COUNTROWS(dim_equipment),
            dim_equipment[status] = "active"
        )
)

// 2.4 Условная агрегация: добыча по сменам
EVALUATE
ADDCOLUMNS(
    SUMMARIZE(
        FILTER(fact_production,
            fact_production[date_id] >= 20240301
            && fact_production[date_id] <= 20240331),
        dim_date[full_date]
    ),
    "Записей смена 1",
        CALCULATE(COUNTROWS(fact_production), fact_production[shift_id] = 1),
    "Записей смена 2",
        CALCULATE(COUNTROWS(fact_production), fact_production[shift_id] = 2),
    "Тонн смена 1",
        CALCULATE(SUM(fact_production[tons_mined]), fact_production[shift_id] = 1),
    "Тонн смена 2",
        CALCULATE(SUM(fact_production[tons_mined]), fact_production[shift_id] = 2)
)

// 2.5 Статистические функции
EVALUATE
VAR _march =
    FILTER(fact_ore_quality,
        fact_ore_quality[date_id] >= 20240301
        && fact_ore_quality[date_id] <= 20240331)
RETURN
ROW(
    "Станд. откл.",  CALCULATE(STDEV.S(fact_ore_quality[fe_content]), _march),
    "Медиана Fe",    CALCULATE(MEDIAN(fact_ore_quality[fe_content]), _march),
    "Перцентиль 90", CALCULATE(
        PERCENTILEX.INC(fact_ore_quality, fact_ore_quality[fe_content], 0.9), _march)
)


// ============================================================
// 3. ФУНКЦИИ ПРЕОБРАЗОВАНИЯ ТИПОВ
// ============================================================

// 3.1 CONVERT — основная функция преобразования
EVALUATE
ROW(
    "Целое",     CONVERT(56.78, INTEGER),
    "Текст",     CONVERT(20240315, STRING),
    "Дробное",   CONVERT("123.45", DOUBLE)
)

// 3.2 INT, VALUE — быстрые преобразования
EVALUATE
ROW(
    "INT от 56.78",     INT(56.78),
    "VALUE от строки",  VALUE("123.45")
)

// 3.3 FORMAT — форматирование дат и чисел
EVALUATE
ROW(
    "Сегодня",        FORMAT(TODAY(), "DD.MM.YYYY"),
    "Полная дата",    FORMAT(TODAY(), "DD MMMM YYYY"),
    "Число",          FORMAT(12345.678, "#,##0.00"),
    "Процент",        FORMAT(0.856, "0.0%")
)

// 3.4 FORMAT для дат из таблицы
EVALUATE
TOPN(5,
    ADDCOLUMNS(
        dim_date,
        "Формат 1", FORMAT(dim_date[full_date], "DD.MM.YYYY"),
        "Формат 2", FORMAT(dim_date[full_date], "DD MMM YYYY"),
        "Только месяц", FORMAT(dim_date[full_date], "MMMM YYYY")
    ),
    dim_date[date_id], ASC
)

// 3.5 DATEVALUE, TIMEVALUE — строка в дату/время
EVALUATE
ROW(
    "Дата из строки", DATEVALUE("2024-03-15"),
    "Время из строки", TIMEVALUE("14:30:00")
)


// ============================================================
// 4. УСЛОВНАЯ ЛОГИКА
// ============================================================

// 4.1 IF — классификация руды по содержанию Fe
EVALUATE
ADDCOLUMNS(
    FILTER(fact_ore_quality,
        fact_ore_quality[date_id] = 20240315),
    "Категория",
        IF(fact_ore_quality[fe_content] >= 65, "Богатая руда",
            IF(fact_ore_quality[fe_content] >= 55, "Средняя руда",
                IF(fact_ore_quality[fe_content] >= 45, "Бедная руда",
                    "Забалансовая")))
)

// 4.2 SWITCH(TRUE(), ...) — более читаемая альтернатива вложенным IF
EVALUATE
ADDCOLUMNS(
    FILTER(fact_ore_quality,
        fact_ore_quality[date_id] = 20240315),
    "Категория",
        SWITCH(TRUE(),
            fact_ore_quality[fe_content] >= 65, "Богатая руда",
            fact_ore_quality[fe_content] >= 55, "Средняя руда",
            fact_ore_quality[fe_content] >= 45, "Бедная руда",
            "Забалансовая"
        )
)

// 4.3 SWITCH — простая форма (аналог простого CASE)
EVALUATE
SUMMARIZE(
    FILTER(fact_production,
        fact_production[date_id] >= 20240301
        && fact_production[date_id] <= 20240331),
    fact_production[shift_id],
    "Название смены",
        SWITCH(
            CALCULATE(MAX(fact_production[shift_id])),
            1, "Утренняя смена",
            2, "Дневная смена",
            3, "Ночная смена",
            "Неизвестная"
        ),
    "Всего тонн", SUM(fact_production[tons_mined])
)

// 4.4 Условная агрегация — кросс-табуляция
EVALUATE
ADDCOLUMNS(
    SUMMARIZE(
        FILTER(fact_ore_quality,
            YEAR(RELATED(dim_date[full_date])) = 2024
            && MONTH(RELATED(dim_date[full_date])) = 3),
        dim_date[full_date]
    ),
    "Хорошие пробы",
        CALCULATE(
            COUNTROWS(fact_ore_quality),
            fact_ore_quality[fe_content] >= 60),
    "Плохие пробы",
        CALCULATE(
            COUNTROWS(fact_ore_quality),
            fact_ore_quality[fe_content] < 60),
    "% хороших",
        DIVIDE(
            CALCULATE(COUNTROWS(fact_ore_quality), fact_ore_quality[fe_content] >= 60),
            COUNTROWS(fact_ore_quality),
            0) * 100
)

// 4.5 COALESCE — подстановка значений по умолчанию
EVALUATE
ADDCOLUMNS(
    FILTER(fact_ore_quality,
        fact_ore_quality[date_id] = 20240315),
    "SiO2 безоп.", COALESCE(fact_ore_quality[sio2_content], 0),
    "Al2O3 безоп.", COALESCE(fact_ore_quality[al2o3_content], 0),
    "Влажн. безоп.", COALESCE(fact_ore_quality[moisture], 0)
)

// 4.6 IF + ISBLANK — альтернатива COALESCE (до DAX 2021)
EVALUATE
ADDCOLUMNS(
    FILTER(fact_ore_quality,
        fact_ore_quality[date_id] = 20240315),
    "SiO2 безоп.",
        IF(ISBLANK(fact_ore_quality[sio2_content]),
           0,
           fact_ore_quality[sio2_content])
)

// 4.7 DIVIDE — безопасное деление (аналог NULLIF + / в SQL)
EVALUATE
ADDCOLUMNS(
    FILTER(fact_production,
        fact_production[date_id] = 20240315),
    "Тонн/рейс",
        DIVIDE(
            fact_production[tons_transported],
            fact_production[trips_count],
            0
        ),
    "Топливо/час",
        DIVIDE(
            fact_production[fuel_consumed_l],
            fact_production[operating_hours],
            0
        )
)


// ============================================================
// 5. РАБОТА С NULL (BLANK)
// ============================================================

// 5.1 ISBLANK — поиск записей с пустыми описаниями простоев
EVALUATE
FILTER(fact_equipment_downtime,
    ISBLANK(fact_equipment_downtime[comment])
)

// 5.2 Подсчёт BLANK значений
EVALUATE
ROW(
    "Всего строк",    COUNTROWS(fact_ore_quality),
    "С SiO2",         COUNT(fact_ore_quality[sio2_content]),
    "Без SiO2",       COUNTROWS(fact_ore_quality) - COUNT(fact_ore_quality[sio2_content]),
    "% пустых",
        DIVIDE(
            COUNTROWS(fact_ore_quality) - COUNT(fact_ore_quality[sio2_content]),
            COUNTROWS(fact_ore_quality),
            0) * 100
)

// 5.3 Арифметика с BLANK — отличие от SQL NULL!
// В DAX: BLANK() + 5 = 5 (BLANK трактуется как 0)
// В SQL:  NULL + 5 = NULL
EVALUATE
ROW(
    "BLANK + 5",     BLANK() + 5,
    "BLANK * 10",    BLANK() * 10,
    "IF BLANK",      IF(ISBLANK(BLANK()), "Пусто", "Есть значение")
)


// ============================================================
// 6. КОМПЛЕКСНЫЙ ПРИМЕР: KPI ЭФФЕКТИВНОСТИ ОБОРУДОВАНИЯ
// ============================================================

EVALUATE
VAR _march =
    FILTER(fact_production,
        fact_production[date_id] >= 20240301
        && fact_production[date_id] <= 20240331)
RETURN
ADDCOLUMNS(
    SUMMARIZE(_march,
        dim_equipment[equipment_name],
        dim_equipment_type[type_name]
    ),
    "Смен",
        CALCULATE(COUNTROWS(fact_production), _march),
    "Всего тонн",
        ROUND(CALCULATE(SUM(fact_production[tons_mined]), _march), 1),
    "Всего часов",
        ROUND(CALCULATE(SUM(fact_production[operating_hours]), _march), 1),
    "Тонн/час",
        ROUND(DIVIDE(
            CALCULATE(SUM(fact_production[tons_mined]), _march),
            CALCULATE(SUM(fact_production[operating_hours]), _march),
            0
        ), 2),
    "Использование %",
        ROUND(DIVIDE(
            CALCULATE(SUM(fact_production[operating_hours]), _march),
            CALCULATE(COUNTROWS(fact_production), _march) * 8,
            0
        ) * 100, 1),
    "Топливо/тонну",
        ROUND(DIVIDE(
            CALCULATE(SUM(fact_production[fuel_consumed_l]), _march),
            CALCULATE(SUM(fact_production[tons_mined]), _march),
            0
        ), 3),
    "Категория",
        SWITCH(TRUE(),
            DIVIDE(
                CALCULATE(SUM(fact_production[tons_mined]), _march),
                CALCULATE(SUM(fact_production[operating_hours]), _march),
                0) > 20, "Высокая",
            DIVIDE(
                CALCULATE(SUM(fact_production[tons_mined]), _march),
                CALCULATE(SUM(fact_production[operating_hours]), _march),
                0) > 12, "Средняя",
            "Низкая"
        )
)
