// ============================================================
// Модуль 2: Примеры DAX-запросов из презентации
// Предприятие «Руда+» — аналитическая модель
// Выполнять в DAX Studio, подключённом к Power BI Desktop
// ============================================================


// ------------------------------------------------------------
// Пример 1: Просмотр содержимого таблицы
// Аналог SQL: SELECT * FROM dim_equipment_type;
// ------------------------------------------------------------

EVALUATE
    dim_equipment_type


// ------------------------------------------------------------
// Пример 2: Фильтрация — активное оборудование
// Аналог SQL: SELECT * FROM dim_equipment WHERE status = 'active';
// ------------------------------------------------------------

EVALUATE
    FILTER(
        dim_equipment,
        dim_equipment[status] = "active"
    )


// ------------------------------------------------------------
// Пример 3: Агрегация — добыча по шахтам
// Аналог SQL:
//   SELECT m.mine_name, SUM(fp.tons_mined) AS "Добыча, т"
//   FROM fact_production fp
//   JOIN dim_mine m ON fp.mine_id = m.mine_id
//   GROUP BY m.mine_name
//   ORDER BY "Добыча, т" DESC;
// ------------------------------------------------------------

EVALUATE
    SUMMARIZECOLUMNS(
        dim_mine[mine_name],
        "Добыча, т", SUM(fact_production[tons_mined])
    )
ORDER BY [Добыча, т] DESC


// ------------------------------------------------------------
// Пример 4: Добыча по шахтам и сменам
// Аналог SQL:
//   SELECT m.mine_name, s.shift_name,
//          SUM(fp.tons_mined), SUM(fp.trips_count)
//   FROM fact_production fp
//   JOIN dim_mine m ON fp.mine_id = m.mine_id
//   JOIN dim_shift s ON fp.shift_id = s.shift_id
//   GROUP BY m.mine_name, s.shift_name
//   ORDER BY SUM(fp.tons_mined) DESC;
// ------------------------------------------------------------

EVALUATE
    SUMMARIZECOLUMNS(
        dim_mine[mine_name],
        dim_shift[shift_name],
        "Добыча, т", SUM(fact_production[tons_mined]),
        "Рейсов",    SUM(fact_production[trips_count])
    )
ORDER BY [Добыча, т] DESC


// ------------------------------------------------------------
// Пример 5: Использование DEFINE — локальная мера
// Блок DEFINE позволяет определить меру в рамках запроса,
// не сохраняя её в модели (аналог CTE в SQL)
// ------------------------------------------------------------

DEFINE
    MEASURE fact_production[Эффективность перевозки] =
        DIVIDE(
            SUM(fact_production[tons_transported]),
            SUM(fact_production[tons_mined]),
            0
        )

EVALUATE
    SUMMARIZECOLUMNS(
        dim_mine[mine_name],
        "Добыто, т", SUM(fact_production[tons_mined]),
        "Перевезено, т", SUM(fact_production[tons_transported]),
        "Эффективность, %", [Эффективность перевозки] * 100
    )


// ------------------------------------------------------------
// Пример 6: VAR ... RETURN — переменные в DAX
// Аналог SQL: WITH cte AS (...) SELECT * FROM cte WHERE ...;
// Задача: средняя добыча по шахтам, только > 100 т
// ------------------------------------------------------------

EVALUATE
VAR mine_totals =
    SUMMARIZECOLUMNS(
        dim_mine[mine_name],
        "avg_tons",
            AVERAGE(fact_production[tons_mined])
    )
RETURN
    FILTER(
        mine_totals,
        [avg_tons] > 100
    )


// ------------------------------------------------------------
// Пример 7: Вычисляемый столбец (определение в модели)
// Этот код НЕ выполняется в DAX Studio как запрос.
// Он показывает синтаксис создания вычисляемого столбца
// в модели Power BI (вкладка "Данные").
// ------------------------------------------------------------

// Возраст оборудования =
//     YEAR(TODAY()) - dim_equipment[year_manufactured]


// ------------------------------------------------------------
// Пример 8: Определение меры в модели
// Этот код создаётся в Power BI Desktop (вкладка "Моделирование")
// или в DAX Studio через блок DEFINE для тестирования.
// ------------------------------------------------------------

// Общая добыча =
//     SUM(fact_production[tons_mined])


// ------------------------------------------------------------
// Пример 9: Просмотр всех столбцов и строк таблицы измерений
// Полезно для первичного знакомства с данными модели
// ------------------------------------------------------------

EVALUATE
    dim_mine

EVALUATE
    dim_shift

EVALUATE
    dim_ore_grade


// ------------------------------------------------------------
// Пример 10: Подсчёт количества записей в факт-таблице
// Аналог SQL: SELECT COUNT(*) FROM fact_production;
// ------------------------------------------------------------

EVALUATE
    ROW(
        "Записей добычи",       COUNTROWS(fact_production),
        "Записей простоев",     COUNTROWS(fact_equipment_downtime),
        "Записей качества",     COUNTROWS(fact_ore_quality),
        "Записей телеметрии",   COUNTROWS(fact_equipment_telemetry)
    )


// ============================================================
// DEFINE COLUMN — вычисляемый столбец в запросе
// ============================================================


// ------------------------------------------------------------
// Пример 11: DEFINE COLUMN — описание оборудования
// Столбец существует только на время запроса.
// Аналог SQL: SELECT e.name || ' (' || t.type_name || ')' ...
// ------------------------------------------------------------

DEFINE
    COLUMN dim_equipment[Полное_описание] =
        dim_equipment[equipment_name]
            & " (" & RELATED(dim_equipment_type[type_name]) & ")"

    COLUMN dim_equipment[Возраст_лет] =
        YEAR(TODAY()) - dim_equipment[year_manufactured]

EVALUATE
    SELECTCOLUMNS(
        FILTER(dim_equipment, dim_equipment[status] = "active"),
        "Оборудование", dim_equipment[Полное_описание],
        "Возраст, лет", dim_equipment[Возраст_лет],
        "Шахта", RELATED(dim_mine[mine_name])
    )
ORDER BY [Возраст, лет] DESC


// ============================================================
// Контекст вычислений и CALCULATE
// ============================================================


// ------------------------------------------------------------
// Пример 12: Контекст фильтра — одна мера, разные результаты
// Одна и та же формула SUM возвращает разные значения
// в зависимости от контекста, в котором вычисляется.
// ------------------------------------------------------------

// 12а: Без контекста — итого по всем данным
DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])

EVALUATE
    ROW("Добыча всего, т", [Добыча_Итого])


// 12б: В контексте шахты — та же мера, но для каждой шахты
DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])

EVALUATE
    ADDCOLUMNS(
        VALUES(dim_mine[mine_name]),
        "Добыча, т", [Добыча_Итого]
    )


// 12в: В контексте шахта + смена
DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])

EVALUATE
    ADDCOLUMNS(
        CROSSJOIN(
            VALUES(dim_mine[mine_name]),
            VALUES(dim_shift[shift_name])
        ),
        "Добыча, т", [Добыча_Итого]
    )
ORDER BY dim_mine[mine_name], dim_shift[shift_name]


// ------------------------------------------------------------
// Пример 13: CALCULATE — фиксированный фильтр
// Мера всегда возвращает добычу шахты "Северная",
// независимо от текущего контекста.
// Аналог SQL: подзапрос с WHERE mine_name = '...'
// ------------------------------------------------------------

DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])
    MEASURE fact_production[Добыча_Северная] =
        CALCULATE(
            [Добыча_Итого],
            dim_mine[mine_id] = 1
        )

EVALUATE
    ADDCOLUMNS(
        VALUES(dim_mine[mine_name]),
        "Добыча шахты, т", [Добыча_Итого],
        "Добыча Северной, т", [Добыча_Северная]
    )


// ------------------------------------------------------------
// Пример 14: CALCULATE + ALL — доля шахты от общей добычи
// ALL(dim_mine) снимает фильтр по шахте.
// Аналог SQL: SUM(...) OVER () — оконная функция без партиции
// ------------------------------------------------------------

DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])
    MEASURE fact_production[Добыча_Всего] =
        CALCULATE(
            [Добыча_Итого],
            ALL(dim_mine)
        )
    MEASURE fact_production[Доля_Шахты] =
        DIVIDE([Добыча_Итого], [Добыча_Всего]) * 100

EVALUATE
    ADDCOLUMNS(
        VALUES(dim_mine[mine_name]),
        "Добыча шахты, т", [Добыча_Итого],
        "Добыча всего, т", [Добыча_Всего],
        "Доля, %", [Доля_Шахты]
    )


// ------------------------------------------------------------
// Пример 15: CALCULATE — комбинация фильтров
// Контекст шахты сохраняется, добавляется фильтр по смене.
// Аналог SQL: SUM(...) FILTER (WHERE s.shift_id = 1)
// ------------------------------------------------------------

DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])
    MEASURE fact_production[Добыча_Смена1] =
        CALCULATE(
            [Добыча_Итого],
            dim_shift[shift_id] = 1
        )

EVALUATE
    ADDCOLUMNS(
        VALUES(dim_mine[mine_name]),
        "Добыча всех смен, т", [Добыча_Итого],
        "Добыча дневной смены, т", [Добыча_Смена1]
    )


// ------------------------------------------------------------
// Пример 16: KEEPFILTERS vs замена фильтра
// Без KEEPFILTERS: фильтр ЗАМЕНЯЕТСЯ → всегда "Северная"
// С KEEPFILTERS: фильтр ПЕРЕСЕКАЕТСЯ → "Южная" AND "Северная" = пусто
// ------------------------------------------------------------

DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])

    MEASURE fact_production[CALCULATE_Замена] =
        CALCULATE(
            [Добыча_Итого],
            dim_mine[mine_id] = 1  -- Северная
        )

    MEASURE fact_production[CALCULATE_Пересечение] =
        CALCULATE(
            [Добыча_Итого],
            KEEPFILTERS(dim_mine[mine_id] = 1)
        )

EVALUATE
    ADDCOLUMNS(
        VALUES(dim_mine[mine_name]),
        "Добыча шахты, т", [Добыча_Итого],
        "Замена (всегда Сев.), т", [CALCULATE_Замена],
        "Пересечение, т", [CALCULATE_Пересечение]
    )


// ------------------------------------------------------------
// Пример 17: CALCULATE — комбинация нескольких фильтров
// Фильтры объединяются через AND.
// Аналог SQL: WHERE mine_id = 1 AND shift_id = 1 AND year = 2025
// ------------------------------------------------------------

DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])
    MEASURE fact_production[Добыча_Сев_Дн_2025] =
        CALCULATE(
            [Добыча_Итого],
            dim_mine[mine_id] = 1,
            dim_shift[shift_id] = 1,
            dim_date[year] = 2025
        )

EVALUATE
    ROW("Добыча Северная, дневная смена, 2025", [Добыча_Сев_Дн_2025])


// ------------------------------------------------------------
// Пример 18: CALCULATE + SAMEPERIODLASTYEAR — сравнение с прошлым годом
// Типовая MES-задача: добыча текущего года vs прошлого.
// Аналог SQL: LAG(...) OVER (ORDER BY year)
// ------------------------------------------------------------

DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])
    MEASURE fact_production[Добыча_Прошлый_Год] =
        CALCULATE(
            [Добыча_Итого],
            SAMEPERIODLASTYEAR(dim_date[full_date])
        )

EVALUATE
    ADDCOLUMNS(
        VALUES(dim_date[year]),
        "Добыча, т", [Добыча_Итого],
        "Прошлый год, т", [Добыча_Прошлый_Год]
    )
ORDER BY dim_date[year]


// ------------------------------------------------------------
// Пример 19: Переход контекста строки → контекст фильтра
// CALCULATE внутри итератора MAXX: контекст строки
// автоматически преобразуется в контекст фильтра.
// Задача: найти максимальную суточную добычу по шахте.
// ------------------------------------------------------------

DEFINE
    MEASURE fact_production[Добыча_Итого] =
        SUM(fact_production[tons_mined])

EVALUATE
    ADDCOLUMNS(
        VALUES(dim_mine[mine_name]),
        "Макс. суточная добыча, т",
            MAXX(
                VALUES(dim_date[full_date]),
                CALCULATE([Добыча_Итого])
            )
    )
